language: php

php:
  - 7.3.15

install:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpunit --colors="always" --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls#z