language: php

php:
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2

install:
  - composer selfupdate
  - composer install

script:
  - ./vendor/bin/phpunit --colors --coverage-text

#after_success:
  #- travis_retry php vendor/bin/coveralls